options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/iam-monitoring-500903/resume-repo/cloudarmor-python:v1'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/iam-monitoring-500903/resume-repo/cloudarmor-python:v1'